apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: dapr-app
  labels:
    app: webserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: us-central1-docker.pkg.dev/gcp-genai-inframod-prj01/dapr-testing/webserver:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: dapr-app
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer