apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: datastore
spec:
  type: state.postgresql
  # Note: setting "version" to "v2" is required to use the v2 of the component
  version: v2
  metadata:
  - name: connectionString
    value: "host=postgres-0.postgres user=postgres password=thisispassword port=5432 dbname=postgres sslmode=disable"