apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "webserver"
        dapr.io/app-port: "8080"
    spec:
      containers:
      - name: webserver
        image: us-central1-docker.pkg.dev/gcp-genai-inframod-prj01/dapr-testing/webserver:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8080
  type: LoadBalancer
